// Code generated by protoc-gen-go. DO NOT EDIT.
// source: db.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	db.proto

It has these top-level messages:
	GetProductsRequest
	GetProductsResponse
	CreateProductRequest
	CreateProductResponse
	UpdateProductRequest
	UpdateProductResponse
	DeleteProductRequest
	DeleteProductResponse
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import api1 "."

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetProductsRequest struct {
}

func (m *GetProductsRequest) Reset()                    { *m = GetProductsRequest{} }
func (m *GetProductsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetProductsRequest) ProtoMessage()               {}
func (*GetProductsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type GetProductsResponse struct {
	Products []*api1.Product    `protobuf:"bytes,1,rep,name=products" json:"products,omitempty"`
	Response *api1.ResponseData `protobuf:"bytes,2,opt,name=response" json:"response,omitempty"`
}

func (m *GetProductsResponse) Reset()                    { *m = GetProductsResponse{} }
func (m *GetProductsResponse) String() string            { return proto.CompactTextString(m) }
func (*GetProductsResponse) ProtoMessage()               {}
func (*GetProductsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetProductsResponse) GetProducts() []*api1.Product {
	if m != nil {
		return m.Products
	}
	return nil
}

func (m *GetProductsResponse) GetResponse() *api1.ResponseData {
	if m != nil {
		return m.Response
	}
	return nil
}

type CreateProductRequest struct {
	Product *api1.Product `protobuf:"bytes,1,opt,name=product" json:"product,omitempty"`
}

func (m *CreateProductRequest) Reset()                    { *m = CreateProductRequest{} }
func (m *CreateProductRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateProductRequest) ProtoMessage()               {}
func (*CreateProductRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreateProductRequest) GetProduct() *api1.Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type CreateProductResponse struct {
	ProductHash string             `protobuf:"bytes,1,opt,name=product_hash,json=productHash" json:"product_hash,omitempty"`
	Response    *api1.ResponseData `protobuf:"bytes,2,opt,name=response" json:"response,omitempty"`
}

func (m *CreateProductResponse) Reset()                    { *m = CreateProductResponse{} }
func (m *CreateProductResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateProductResponse) ProtoMessage()               {}
func (*CreateProductResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CreateProductResponse) GetProductHash() string {
	if m != nil {
		return m.ProductHash
	}
	return ""
}

func (m *CreateProductResponse) GetResponse() *api1.ResponseData {
	if m != nil {
		return m.Response
	}
	return nil
}

type UpdateProductRequest struct {
	Product *api1.Product `protobuf:"bytes,1,opt,name=product" json:"product,omitempty"`
}

func (m *UpdateProductRequest) Reset()                    { *m = UpdateProductRequest{} }
func (m *UpdateProductRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateProductRequest) ProtoMessage()               {}
func (*UpdateProductRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *UpdateProductRequest) GetProduct() *api1.Product {
	if m != nil {
		return m.Product
	}
	return nil
}

type UpdateProductResponse struct {
	ProductHash string             `protobuf:"bytes,1,opt,name=product_hash,json=productHash" json:"product_hash,omitempty"`
	Response    *api1.ResponseData `protobuf:"bytes,2,opt,name=response" json:"response,omitempty"`
}

func (m *UpdateProductResponse) Reset()                    { *m = UpdateProductResponse{} }
func (m *UpdateProductResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateProductResponse) ProtoMessage()               {}
func (*UpdateProductResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UpdateProductResponse) GetProductHash() string {
	if m != nil {
		return m.ProductHash
	}
	return ""
}

func (m *UpdateProductResponse) GetResponse() *api1.ResponseData {
	if m != nil {
		return m.Response
	}
	return nil
}

type DeleteProductRequest struct {
	ProductHash string `protobuf:"bytes,1,opt,name=product_hash,json=productHash" json:"product_hash,omitempty"`
}

func (m *DeleteProductRequest) Reset()                    { *m = DeleteProductRequest{} }
func (m *DeleteProductRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteProductRequest) ProtoMessage()               {}
func (*DeleteProductRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *DeleteProductRequest) GetProductHash() string {
	if m != nil {
		return m.ProductHash
	}
	return ""
}

type DeleteProductResponse struct {
	Response *api1.ResponseData `protobuf:"bytes,1,opt,name=response" json:"response,omitempty"`
}

func (m *DeleteProductResponse) Reset()                    { *m = DeleteProductResponse{} }
func (m *DeleteProductResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteProductResponse) ProtoMessage()               {}
func (*DeleteProductResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *DeleteProductResponse) GetResponse() *api1.ResponseData {
	if m != nil {
		return m.Response
	}
	return nil
}

func init() {
	proto.RegisterType((*GetProductsRequest)(nil), "api.GetProductsRequest")
	proto.RegisterType((*GetProductsResponse)(nil), "api.GetProductsResponse")
	proto.RegisterType((*CreateProductRequest)(nil), "api.CreateProductRequest")
	proto.RegisterType((*CreateProductResponse)(nil), "api.CreateProductResponse")
	proto.RegisterType((*UpdateProductRequest)(nil), "api.UpdateProductRequest")
	proto.RegisterType((*UpdateProductResponse)(nil), "api.UpdateProductResponse")
	proto.RegisterType((*DeleteProductRequest)(nil), "api.DeleteProductRequest")
	proto.RegisterType((*DeleteProductResponse)(nil), "api.DeleteProductResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for DatabaseAPI service

type DatabaseAPIClient interface {
	// ListProducts
	ListProducts(ctx context.Context, in *GetProductsRequest, opts ...grpc.CallOption) (*GetProductsResponse, error)
	// CreateProduct
	CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*CreateProductResponse, error)
	// UpdateProduct
	UpdateProduct(ctx context.Context, in *UpdateProductRequest, opts ...grpc.CallOption) (*UpdateProductResponse, error)
	// DeleteProduct
	DeleteProduct(ctx context.Context, in *DeleteProductRequest, opts ...grpc.CallOption) (*DeleteProductResponse, error)
}

type databaseAPIClient struct {
	cc *grpc.ClientConn
}

func NewDatabaseAPIClient(cc *grpc.ClientConn) DatabaseAPIClient {
	return &databaseAPIClient{cc}
}

func (c *databaseAPIClient) ListProducts(ctx context.Context, in *GetProductsRequest, opts ...grpc.CallOption) (*GetProductsResponse, error) {
	out := new(GetProductsResponse)
	err := grpc.Invoke(ctx, "/api.DatabaseAPI/ListProducts", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseAPIClient) CreateProduct(ctx context.Context, in *CreateProductRequest, opts ...grpc.CallOption) (*CreateProductResponse, error) {
	out := new(CreateProductResponse)
	err := grpc.Invoke(ctx, "/api.DatabaseAPI/CreateProduct", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseAPIClient) UpdateProduct(ctx context.Context, in *UpdateProductRequest, opts ...grpc.CallOption) (*UpdateProductResponse, error) {
	out := new(UpdateProductResponse)
	err := grpc.Invoke(ctx, "/api.DatabaseAPI/UpdateProduct", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *databaseAPIClient) DeleteProduct(ctx context.Context, in *DeleteProductRequest, opts ...grpc.CallOption) (*DeleteProductResponse, error) {
	out := new(DeleteProductResponse)
	err := grpc.Invoke(ctx, "/api.DatabaseAPI/DeleteProduct", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DatabaseAPI service

type DatabaseAPIServer interface {
	// ListProducts
	ListProducts(context.Context, *GetProductsRequest) (*GetProductsResponse, error)
	// CreateProduct
	CreateProduct(context.Context, *CreateProductRequest) (*CreateProductResponse, error)
	// UpdateProduct
	UpdateProduct(context.Context, *UpdateProductRequest) (*UpdateProductResponse, error)
	// DeleteProduct
	DeleteProduct(context.Context, *DeleteProductRequest) (*DeleteProductResponse, error)
}

func RegisterDatabaseAPIServer(s *grpc.Server, srv DatabaseAPIServer) {
	s.RegisterService(&_DatabaseAPI_serviceDesc, srv)
}

func _DatabaseAPI_ListProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseAPIServer).ListProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.DatabaseAPI/ListProducts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseAPIServer).ListProducts(ctx, req.(*GetProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseAPI_CreateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseAPIServer).CreateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.DatabaseAPI/CreateProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseAPIServer).CreateProduct(ctx, req.(*CreateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseAPI_UpdateProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseAPIServer).UpdateProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.DatabaseAPI/UpdateProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseAPIServer).UpdateProduct(ctx, req.(*UpdateProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DatabaseAPI_DeleteProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DatabaseAPIServer).DeleteProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.DatabaseAPI/DeleteProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DatabaseAPIServer).DeleteProduct(ctx, req.(*DeleteProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DatabaseAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.DatabaseAPI",
	HandlerType: (*DatabaseAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListProducts",
			Handler:    _DatabaseAPI_ListProducts_Handler,
		},
		{
			MethodName: "CreateProduct",
			Handler:    _DatabaseAPI_CreateProduct_Handler,
		},
		{
			MethodName: "UpdateProduct",
			Handler:    _DatabaseAPI_UpdateProduct_Handler,
		},
		{
			MethodName: "DeleteProduct",
			Handler:    _DatabaseAPI_DeleteProduct_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "db.proto",
}

func init() { proto.RegisterFile("db.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 314 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x93, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x9b, 0x16, 0xb4, 0x4e, 0xe2, 0xc1, 0x35, 0xc5, 0x98, 0x53, 0xdd, 0x83, 0xe4, 0x62,
	0x0e, 0xf1, 0xe4, 0x45, 0x90, 0x16, 0xad, 0xe0, 0xa1, 0x04, 0x3c, 0xcb, 0xc6, 0x2c, 0x24, 0x50,
	0x9b, 0x35, 0xbb, 0xfd, 0x5f, 0xfe, 0x44, 0x71, 0x33, 0x09, 0xdd, 0x64, 0xa1, 0xa0, 0x78, 0x9d,
	0x79, 0xef, 0xdb, 0x97, 0x99, 0x09, 0x4c, 0xf3, 0x2c, 0x16, 0x75, 0xa5, 0x2a, 0x32, 0x61, 0xa2,
	0x0c, 0xdd, 0x8f, 0x2a, 0xe7, 0x9b, 0xa6, 0x42, 0x7d, 0x20, 0x4f, 0x5c, 0xad, 0xeb, 0x2a, 0xdf,
	0xbd, 0x2b, 0x99, 0xf2, 0xcf, 0x1d, 0x97, 0x8a, 0x6e, 0xe1, 0xdc, 0xa8, 0x4a, 0x51, 0x6d, 0x25,
	0x27, 0x11, 0x4c, 0x05, 0xd6, 0x02, 0x67, 0x3e, 0x89, 0xdc, 0xc4, 0x8b, 0x99, 0x28, 0x63, 0x14,
	0xa6, 0x5d, 0x97, 0xdc, 0xc0, 0xb4, 0x46, 0x57, 0x30, 0x9e, 0x3b, 0x91, 0x9b, 0x9c, 0x69, 0x65,
	0x8b, 0x5a, 0x32, 0xc5, 0xd2, 0x4e, 0x42, 0xef, 0xc1, 0x5f, 0xd4, 0x9c, 0x29, 0xde, 0x92, 0x9a,
	0x1c, 0xe4, 0x1a, 0x8e, 0x11, 0x19, 0x38, 0x9a, 0x62, 0xbe, 0xd7, 0x36, 0x69, 0x09, 0xb3, 0x9e,
	0x1f, 0x13, 0x5f, 0x81, 0x87, 0x9a, 0xb7, 0x82, 0xc9, 0x42, 0x53, 0x4e, 0x52, 0x17, 0x6b, 0x2b,
	0x26, 0x8b, 0x5f, 0x44, 0x7d, 0x15, 0xf9, 0x9f, 0xa2, 0xf6, 0xfc, 0xff, 0x16, 0xf5, 0x0e, 0xfc,
	0x25, 0xdf, 0xf0, 0x41, 0xd4, 0xc3, 0x2f, 0xd1, 0x47, 0x98, 0xf5, 0xac, 0x98, 0x72, 0x3f, 0x82,
	0x73, 0x30, 0x42, 0xf2, 0x35, 0x06, 0xf7, 0xa7, 0x94, 0x31, 0xc9, 0x1f, 0xd6, 0xcf, 0x64, 0x01,
	0xde, 0x4b, 0x29, 0xbb, 0xcb, 0x22, 0x17, 0xda, 0x3c, 0xbc, 0xc0, 0x30, 0x18, 0x36, 0xf0, 0xab,
	0x46, 0x64, 0x05, 0xa7, 0xc6, 0xb6, 0xc9, 0xa5, 0x16, 0xdb, 0x2e, 0x28, 0x0c, 0x6d, 0xad, 0x7d,
	0x92, 0xb1, 0x0c, 0x24, 0xd9, 0x16, 0x8c, 0x24, 0xeb, 0xee, 0x1a, 0x92, 0x31, 0x30, 0x24, 0xd9,
	0xe6, 0x8f, 0x24, 0xeb, 0x7c, 0xe9, 0x28, 0x3b, 0xd2, 0x3f, 0xe6, 0xed, 0x77, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x03, 0xc5, 0x88, 0x36, 0xb6, 0x03, 0x00, 0x00,
}
