// Code generated by protoc-gen-go. DO NOT EDIT.
// source: watcher.proto

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	watcher.proto

It has these top-level messages:
	GetProductsRequest
	GetProductsResponse
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import api1 "."

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetProductsRequest struct {
}

func (m *GetProductsRequest) Reset()                    { *m = GetProductsRequest{} }
func (m *GetProductsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetProductsRequest) ProtoMessage()               {}
func (*GetProductsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type GetProductsResponse struct {
	Products []*api1.Product    `protobuf:"bytes,1,rep,name=products" json:"products,omitempty"`
	Response *api1.ResponseData `protobuf:"bytes,2,opt,name=response" json:"response,omitempty"`
}

func (m *GetProductsResponse) Reset()                    { *m = GetProductsResponse{} }
func (m *GetProductsResponse) String() string            { return proto.CompactTextString(m) }
func (*GetProductsResponse) ProtoMessage()               {}
func (*GetProductsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetProductsResponse) GetProducts() []*api1.Product {
	if m != nil {
		return m.Products
	}
	return nil
}

func (m *GetProductsResponse) GetResponse() *api1.ResponseData {
	if m != nil {
		return m.Response
	}
	return nil
}

func init() {
	proto.RegisterType((*GetProductsRequest)(nil), "api.GetProductsRequest")
	proto.RegisterType((*GetProductsResponse)(nil), "api.GetProductsResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for WatcherAPI service

type WatcherAPIClient interface {
	// GetProducts
	GetProducts(ctx context.Context, in *GetProductsRequest, opts ...grpc.CallOption) (*GetProductsResponse, error)
}

type watcherAPIClient struct {
	cc *grpc.ClientConn
}

func NewWatcherAPIClient(cc *grpc.ClientConn) WatcherAPIClient {
	return &watcherAPIClient{cc}
}

func (c *watcherAPIClient) GetProducts(ctx context.Context, in *GetProductsRequest, opts ...grpc.CallOption) (*GetProductsResponse, error) {
	out := new(GetProductsResponse)
	err := grpc.Invoke(ctx, "/api.WatcherAPI/GetProducts", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for WatcherAPI service

type WatcherAPIServer interface {
	// GetProducts
	GetProducts(context.Context, *GetProductsRequest) (*GetProductsResponse, error)
}

func RegisterWatcherAPIServer(s *grpc.Server, srv WatcherAPIServer) {
	s.RegisterService(&_WatcherAPI_serviceDesc, srv)
}

func _WatcherAPI_GetProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatcherAPIServer).GetProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.WatcherAPI/GetProducts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatcherAPIServer).GetProducts(ctx, req.(*GetProductsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _WatcherAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.WatcherAPI",
	HandlerType: (*WatcherAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProducts",
			Handler:    _WatcherAPI_GetProducts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "watcher.proto",
}

func init() { proto.RegisterFile("watcher.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 174 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4f, 0x2c, 0x49,
	0xce, 0x48, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0xc8, 0x94, 0xe2,
	0xce, 0xcd, 0x4f, 0x49, 0xcd, 0x81, 0x88, 0x28, 0x89, 0x70, 0x09, 0xb9, 0xa7, 0x96, 0x04, 0x14,
	0xe5, 0xa7, 0x94, 0x26, 0x97, 0x14, 0x07, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x28, 0xe5, 0x71,
	0x09, 0xa3, 0x88, 0x16, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0x69, 0x70, 0x71, 0x14, 0x40, 0xc5,
	0x24, 0x18, 0x15, 0x98, 0x35, 0xb8, 0x8d, 0x78, 0xf4, 0x12, 0x0b, 0x32, 0xf5, 0xa0, 0x0a, 0x83,
	0xe0, 0xb2, 0x42, 0xba, 0x5c, 0x1c, 0x45, 0x50, 0x5d, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0xdc, 0x46,
	0x82, 0x60, 0x95, 0x30, 0xa3, 0x5c, 0x12, 0x4b, 0x12, 0x83, 0xe0, 0x4a, 0x8c, 0x02, 0xb8, 0xb8,
	0xc2, 0x21, 0x0e, 0x75, 0x0c, 0xf0, 0x14, 0x72, 0xe2, 0xe2, 0x46, 0xb2, 0x5d, 0x48, 0x1c, 0xac,
	0x13, 0xd3, 0x95, 0x52, 0x12, 0x98, 0x12, 0x10, 0xf3, 0x94, 0x18, 0x92, 0xd8, 0xc0, 0xde, 0x33,
	0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xc7, 0x0d, 0x7f, 0x61, 0x01, 0x01, 0x00, 0x00,
}
